# https://www.netlingo.com/acronyms.php
# https://blog.adioma.com/internet-acronyms-intro-list-infographic/
acronyms = {
    'btw': 'by the way',
    'afaik': 'as far as i know',
    'afk': 'away from keyboard',
    'asap': 'as soon as possible',
    'atm': 'at the moment',
    'af': 'as fuck',
    'bbl': 'be back later',
    'brb': 'be right back',
    'bozo' : 'idiot',
    'b4': 'before',
    'bs': 'bullshit',
    'cya': 'see ya',
    'dunno': 'i don\'t know',
    'dae': 'does anyone else',
    'eli5': 'explain like i\'m five',
    'fyi': 'for your information',
    'ftw' : 'for the win',
    'faq': 'frequently asked questions',
    'goat': 'greatest of all time',
    'gg': 'good game',
    'gr8': 'great',
    'gaf': 'give a fuck',
    'idgaf': 'i don\' give a fuck',
    'imo': 'in my opinion',
    'ion': 'i don\'t',
    'imho': 'in my honest opinion',
    'iirc': 'if i remember correctly',
    'irl': 'in real life',
    'idc': 'i don\'t care',
    'l8r': 'later',
    'ikr': 'i know right',
    'jk': 'joke',
    'l': 'loss',
    'm8': 'mate',
    'mrw': 'my reaction when',
    'mfw': 'my face when',
    'mfrs': 'bad',
    'mv': 'music video',
    'ngl': 'not going to lie',
    'pita': 'pain in the ass',
    'pog': 'awesome',
    'pogchamp': 'legend',
    'thx': 'thank you',
    'ty': 'thank you',
    'til': 'today i learned',
    'tbh': 'to be honest',
    'stfu': 'shut up',
    'smh': 'shake my head',
    'yk': 'you know',
    'u': 'you',
    'y': 'why',
    'r': 'are',
    'ur': 'your',
    'w8': 'wait',
    '2nite': 'tonight',
}

smileys = {
    ':‑)' : 'smile',
    ':)' : 'smile',
    ':\')' : 'smile',
    ':\'-)' : 'smile',
    ':-]' : 'smile',
    ':]' : 'smile',
    ':-3' : 'smile',
    ':3' : 'smile',
    ':->' : 'smile',
    ':>': 'smile',
    '8-)' : 'smile',
    '8)' : 'smile',
    ':-}' : 'smile',
    ':}' : 'smile',
    ':o)' : 'smile',
    ':c)' : 'smile',
    ':^)' : 'smile',
    '=]' : 'smile',
    '=)' : 'smile',
    '(:' : 'smile',
    ':))' : 'smile',
    ':-))' : 'smile',
    ';‑)' : 'smile',
    ';)' : 'smile',
    ':‑P' : 'smile',
    ':P' : 'smile',
    '☺️' : 'smile',
    '🙂' : 'smile',
    '😊' : 'smile',
    '😀' : 'smile',
    '😁' : 'smile',
    '😺' : 'smile',
    '😸': 'smile',
    '😻' : 'smile',
    '😅' : 'smile',
    '🙃' : 'smile',
    '😇' : 'smile',
    '🥰' :'smile',
    '🤩' : 'smile',
    '😍' : 'smile',
    '🤠' : 'smile',
    '😎' : 'smile',
    '😻' : 'smile',
    '🤓' : 'smile',
    ':‑D' : 'laugh',
    ':D' : 'laugh',
    '8‑D' : 'laugh',
    '8D' : 'laugh',
    'x‑D' : 'laugh',
    'xD' : 'laugh',
    'X‑D' : 'laugh',
    'XD' : 'laugh',
    '=D' : 'laugh',
    '=3' : 'laugh',
    'B^D' : 'laugh',
    'c:' : 'laugh',
    'C:' : 'laugh',
    '😃' : 'laugh',
    '😀' : 'laugh',
    '😄' : 'laugh',
    '😆' : 'laugh',
    '💀' : 'laugh',
    '😹' : 'laugh',
    '🤣' : 'laugh',
    '😂' : 'laugh',
    '🤭' : 'laugh',
    '😬' : 'laugh',
    ':‑(' : 'sad',
    ':\'‑(' : 'sad',
    ':\'(' : 'sad',
    ':(' : 'sad',
    ':‑c' : 'sad',
    ':c' : 'sad',
    ':‑<' : 'sad',
    ':<' : 'sad',
    ':‑[' : 'sad',
    ':[' : 'sad',
    ':-||' : 'sad',
    ':{' : 'sad',
    ':@' : 'sad',
    ':(' : 'sad',
    ';(' : 'sad',
    ':-/' : 'sad',
    ':/' : 'sad',
    '=/' : 'sad',
    '=\\' : 'sad',
    ':L' : 'sad',
    '☹️' : 'sad',
    '🙁' : 'sad',
    '😞' : 'sad',
    '😔' : 'sad',
    '😟' : 'sad',
    '😣' : 'sad',
    '😖' : 'sad',
    '😧' : 'sad',
    '😦' : 'sad',
    '🤔' : 'sad',
    '😕' : 'sad',
    '😟' : 'sad',
    '🤕' : 'sad',
    '🥺' : 'sad',
    '😨' : 'sad',
    '😰' : 'sad',
    '😥' : 'sad',
    '😢' : 'sad',
    '😭' : 'sad',
    '😩' : 'sad',
    '😿' : 'sad',
    '💔' : 'sad',
    '>:[' : 'angry',
    '>:(' : 'angry',
    '😡' : 'angry',
    '😠' : 'angry',
    '😤' : 'angry',
    '🤬' : 'angry',
    '👿' : 'angry',
    'D‑\':' : 'scared',
    'D:' : 'scared',
    'D8' : 'scared',
    'D;' : 'scared',
    'D=' : 'scared',
    '😱' : 'scared',
    '🙀' : 'scared',
    '🤢' : 'disgusting',
    '🤮' : 'disgusting',
    ':‑|' : 'neutral',
    ':|' : 'neutral',
    '😐' : 'neutral',
    '😑' : 'neutral',
    '🤐' : 'neutral',
    '😶' : 'neutral',
    '😳' : 'embarrassed',
    ':o' : 'surprised',
    ':O' : 'surprised',
    ':-o' : 'surprised',
    ':-O' : 'surprised',
    ':-0' : 'surprised',
    ':0' : 'surprised',
    'O_O' : 'surprised',
    'o‑o' : 'surprised',
    'O_o' : 'surprised',
    'o_O' : 'surprised',
    'o_o' : 'surprised',
    'O-O' : 'surprised',
    '😮' : 'surprised',
    '😯' : 'surprised',
    '😲' : 'surprised',
    '❤' : 'love',
    '💘' : 'love',
    '💝' : 'love',
    '💖' : 'love',
    '💗' : 'love',
    '💓' : 'love',
    '💞' : 'love',
    '💕' : 'love',
    '💟' : 'love',
    '❣️' : 'love',
    '❤️' : 'love',
    '🧡' : 'love',
    '💛' : 'love',
    '💚' : 'love',
    '💙' : 'love',
    '💜' : 'love',
    '🤎' : 'love',
    '🖤' : 'love',
    '🤍' : 'love',
    '🔥' : 'good',
    '👌' : 'good',
    '👌🏻' : 'good',
    '👌🏼' : 'good',
    '👌🏽' : 'good',
    '👌🏾' : 'good',
    '👌🏿' : 'good',
    '👍' : 'good',
    '👍🏻' : 'good',
    '👍🏼' : 'good',
    '👍🏽' : 'good',
    '👍🏾' : 'good',
    '👍🏿' : 'good',
    '👏' : 'good',
    '👏🏻' : 'good',
    '👏🏼' : 'good',
    '👏🏽' : 'good',
    '👏🏾' : 'good',
    '👏🏿' : 'good',
    '💯' : 'good',
    '🖕' : 'bad',
    '🖕🏻' : 'bad',
    '🖕🏼' : 'bad',
    '🖕🏽' : 'bad',
    '🖕🏾' : 'bad',
    '🖕🏿' : 'bad',
    '👎' : 'bad',
    '👎🏻' : 'bad',
    '👎🏼' : 'bad',
    '👎🏽' : 'bad',
    '👎🏾' : 'bad',
    '👎🏿' : 'bad',
    '💩' : 'bad',
    '🤦' : 'disappointed', 
    '🤦🏻' : 'disappointed', 
    '🤦🏼' : 'disappointed',
    '🤦🏽' : 'disappointed', 
    '🤦🏾' : 'disappointed',
    '🤦🏿' : 'disappointed', 
    '🤦‍♂️' : 'disappointed', 
    '🤦🏻‍♂️' : 'disappointed', 
    '🤦🏼‍♂️' : 'disappointed',
    '🤦🏽‍♂️' : 'disappointed', 
    '🤦🏾‍♂️' : 'disappointed',
    '🤦🏿‍♂️' : 'disappointed', 
    '🤦‍♀️' : 'disappointed', 
    '🤦🏻‍♀️' : 'disappointed', 
    '🤦🏼‍♀️' : 'disappointed',
    '🤦🏽‍♀️' : 'disappointed', 
    '🤦🏾‍♀️' : 'disappointed',
    '🤦🏿‍♀️' : 'disappointed'

}

sent_acronyms = {
    'lol' : 'laugh',
    'rofl' : 'laugh',
    'roflol' : 'laugh',
    'roflmao' : 'laugh',
    'lmao' : 'laugh',
    'lmfao' : 'laugh'
}